In [3]:
!pip install opencv-python
!pip install pyautogui

     |████████████████████████████████| 59 kB 1.7 MB/s eta 0:00:01
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
     |████████████████████████████████| 578 kB 4.9 MB/s eta 0:00:01
     |████████████████████████████████| 58 kB 13.0 MB/s eta 0:00:01
     |████████████████████████████████| 226 kB 52.9 MB/s eta 0:00:01
     |████████████████████████████████| 388 kB 27.6 MB/s eta 0:00:01
     |████████████████████████████████| 45 kB 7.7 MB/s  eta 0:00:01


     |████████████████████████████████| 40 kB 12.2 MB/s eta 0:00:01
  Created wheel for pyautogui: filename=PyAutoGUI-0.9.53-py3-none-any.whl size=36613 sha256=f0efacbee949d27d78b13a93012ded2d90b25b54517abaa98a843e0486d75750
  Stored in directory: /Users/brandonliu/Library/Caches/pip/wheels/d8/97/e4/d2edca92a87d3b5fbfb527264750a17b4ba297b9a7cab6e67f
  Created wheel for pygetwindow: filename=PyGetWindow-0.0.9-py3-none-any.whl size=11080 sha256=c12fb09aebb6e02b0522aabef681058a177f113d91fa3e9ccf9a5aed5bbfc7bf
  Stored in directory: /Users/brandonliu/Library/Caches/pip/wheels/44/ab/20/423c3a444793767e4e41f8377bc902f77bee212e68dcce85a5
  Created wheel for pyscreeze: filename=PyScreeze-0.1.28-py3-none-any.whl size=13009 sha256=8e8d5ea9a8d71298a4db2891c36141d04d73edac68fa4ec186071ce5304a334f
  Stored in directory: /Users/brandonliu/Library/Caches/pip/wheels/a2/5b/86/99f1d8fac5d92de0ccb3f0d4ad15e3f4278baf75a9b0f20b93
  Created wheel for PyTweening: filename=pytweening-1.0.4-py3-none-any.whl si

In [6]:
import cv2
import numpy as np
import os
import pyautogui
import time

In [7]:
def add_Objects(arr, directory):
    for file in os.listdir(directory):
        if file[0] != '.':
            f = os.path.join(directory, file)
            if os.path.isfile(f):
                arr.append(f)

In [4]:
## Addes each image to the corresponding object array
## prints each object in each obj arr

board_img = cv2.imread('camp_img.png')
sell_Once_Objects = []
sell_Once_Objects_Directory = 'Object_Images_Desktop\\Sell_Once_Objects'

sell_Twice_Objects = []
sell_Twice_Objects_Directory = 'Object_Images_Desktop\\Sell_Twice_Objects'

tap_Once_Objects = []
tap_Once_Objects_Directory = 'Object_Images_Desktop\\Tap_Once_Objects'

tap_Twice_Objects = []
tap_Twice_Objects_Directory = 'Object_Images_Desktop\\Tap_Twice_Objects'

add_Objects(sell_Once_Objects, sell_Once_Objects_Directory)
add_Objects(sell_Twice_Objects, sell_Twice_Objects_Directory)
add_Objects(tap_Once_Objects, tap_Once_Objects_Directory)
add_Objects(tap_Twice_Objects, tap_Twice_Objects_Directory)

obj_arrs = [sell_Once_Objects, sell_Twice_Objects, tap_Once_Objects, tap_Twice_Objects]

for arr in obj_arrs:
    for obj in arr:
        print(obj)
# for filename in os.listdir(directory):
#     if filename[0] != '.':
#         f = os.path.join(directory, filename)
#         # checking if it is a file
#         if os.path.isfile(f):
#             obj_pathnames.append(f)
#             obj_arr.append(cv2.imread(f, cv2.IMREAD_UNCHANGED))

FileNotFoundError: [Errno 2] No such file or directory: 'Object_Images_Desktop\\Sell_Once_Objects'

In [8]:
## Test for macs
obj_arr = []
add_Objects(obj_arr, "Object_Images_Mac")
print(obj_arr)

['Object_Images_Mac/Magic_Coin_Bronze.PNG', 'Object_Images_Mac/Tiny_Magic_Coin.PNG', 'Object_Images_Mac/Emerald_Plains_Grass.PNG', 'Object_Images_Mac/Radiant_Egg_Chest_Wooden.png', 'Object_Images_Mac/Dragon_Egg_Chest_Red.png', 'Object_Images_Mac/Dragon_Egg_Chest_Stone.PNG', 'Object_Images_Mac/Dragon_Nest_Vault_Stone.png']


In [1]:
## Initializes Rectangles to hold the correct rectangles corresponding to the object arrays
## Prints how many rectangles in each arr
## slight issue with tiny magic coins identifying as egg chest wooden, but hopefully i can add temporary fixes to that for the time 
## being and figure out how to fix it altogether using confidence later

imss = pyautogui.screenshot("imss.png")
imsscv = cv2.imread('imss.png')
rectangles = [[] for _ in range(4)]
rectangles_with_int = [[] for _ in range(4)]
for i, path_arr in enumerate(obj_arrs):
    for img in path_arr:
        result = pyautogui.locateAllOnScreen(img, grayscale=False, confidence=0.65)
        for pos in result:
            rectangles[i].append(pos)
            rectangles[i].append(pos)
    rectangles[i], weights = cv2.groupRectangles(rectangles[i], 1, 0.2)
    print(len(rectangles[i]))
    for j, pos in enumerate(rectangles[i]):
        b = int((pos[1] - (-0.217 * pos[0])) / 20)
        rectangles_with_int[i].append((*pos,b))
    rectangles[i] = np.array(rectangles[i])
    for pos in rectangles[i]:
        cv2.rectangle(imsscv, (pos[0],pos[1]), (pos[0]+pos[2],pos[1]+pos[3]), (0,255,255), 2)
    if  len(rectangles[i]) > 1:
        xvals = rectangles[i][:,0]
        yvals = new_with_int[i][:,4]
        rectangles[i] = rectangles[i][np.lexsort((xvals, yvals))]


NameError: name 'pyautogui' is not defined

In [9]:
# Test for Mac
imss = pyautogui.screenshot("imss.png")
imsscv = cv2.imread('imss.png')
rectangles = [[] for _ in range(4)]
rectangles_with_int = [[] for _ in range(4)]
for img in obj_arr:
    result = pyautogui.locateAllOnScreen(img, grayscale=False, confidence=0.65)
    for pos in result:
        rectangles[1].append(pos)
        rectangles[1].append(pos)
rectangles[1], weights = cv2.groupRectangles(rectangles[1], 1, 0.2)
print(len(rectangles[1]))
for j, pos in enumerate(rectangles[1]):
    b = int((pos[1] - (-0.217 * pos[0])) / 20)
    rectangles_with_int[1].append((*pos,b))
rectangles_with_int[1] = np.array(rectangles_with_int[1])
rectangles_with_int = np.array(rectangles_with_int, dtype=object)
#for pos in rectangles[1]:
    #cv2.rectangle(imsscv, (pos[0],pos[1]), (pos[0]+pos[2],pos[1]+pos[3]), (0,255,255), 2)
if len(rectangles[1]) > 1:
    xvals = rectangles[1][:,0]
    yvals = rectangles_with_int[1][:,4]
    rectangles[1] = rectangles[1][np.lexsort((xvals, yvals))]
    rectangles_with_int[1] = rectangles_with_int[1][np.lexsort((xvals,yvals))]


33


In [10]:
print(rectangles[1])

[[  49   98   23   25]
 [  89   98   23   25]
 [ 129   98   23   25]
 [1961   90   23   25]
 [2001   90   23   25]
 [ 747  583   34   31]
 [ 838  602   34   31]
 [1220  518   34   31]
 [1412  477   34   31]
 [1247  551   34   31]
 [1311  537   34   31]
 [1466  542   34   31]
 [1236  630   34   31]
 [1492  574   34   31]
 [1556  560   34   31]
 [1391  634   34   31]
 [1453  620   34   31]
 [ 334  896   35   35]
 [ 715  819   34   31]
 [ 357  935   34   31]
 [1380  712   34   31]
 [ 512  939   34   31]
 [1625  736   34   31]
 [1880  680   34   31]
 [1525  789   34   34]
 [1588  782   34   31]
 [1489  836   35   35]
 [ 592 1036   34   31]
 [1294  884   34   31]
 [1422  856   34   31]
 [1667  876   38   32]
 [1730  855   39   39]
 [ 546 1154   35   35]]


In [18]:
imss = pyautogui.screenshot("imss.png")
imsscv = cv2.imread('imss.png')
tup = (
    12,13,14
)
for x in tup:
    pos = rectangles[1][x]
    cv2.rectangle(imsscv, (pos[0],pos[1]), (pos[0]+pos[2],pos[1]+pos[3]), (0,255,255), 2)
cv2.imshow('Result', imsscv)
cv2.waitKey(0)
cv2.destroyAllWindows()
cv2.waitKey(1)

-1

In [16]:
print(rectangles_with_int[1])

[[  49   98   23   25    5]
 [  89   98   23   25    5]
 [ 129   98   23   25    6]
 [1961   90   23   25   25]
 [2001   90   23   25   26]
 [ 747  583   34   31   37]
 [ 838  602   34   31   39]
 [1220  518   34   31   39]
 [1412  477   34   31   39]
 [1247  551   34   31   41]
 [1311  537   34   31   41]
 [1466  542   34   31   43]
 [1236  630   34   31   44]
 [1492  574   34   31   44]
 [1556  560   34   31   44]
 [1391  634   34   31   46]
 [1453  620   34   31   46]
 [ 334  896   35   35   48]
 [ 715  819   34   31   48]
 [ 357  935   34   31   50]
 [1380  712   34   31   50]
 [ 512  939   34   31   52]
 [1625  736   34   31   54]
 [1880  680   34   31   54]
 [1525  789   34   34   55]
 [1588  782   34   31   56]
 [1489  836   35   35   57]
 [ 592 1036   34   31   58]
 [1294  884   34   31   58]
 [1422  856   34   31   58]
 [1667  876   38   32   61]
 [1730  855   39   39   61]
 [ 546 1154   35   35   63]]


In [ ]:
## Lowest level is 35
## highest is 18

In [143]:
(314-432)/(991-447)

-0.21691176470588236

In [16]:
## After iniializing rectanlges, run to see where they are
cv2.imshow('Result', imsscv)
cv2.waitKey(0)
cv2.destroyAllWindows()
cv2.waitKey(1)

-1

In [148]:
## does the same thing as previously, just shows the rectangles from each obj arr
## Care may run into issues with screenshot including the previous imshow
    
imss = pyautogui.screenshot("imss.png")
imsscv = cv2.imread('imss.png')
rectangles = [[] for _ in range(4)]
for i, path_arr in enumerate(obj_arrs):
    imsscvnew = imsscv.copy()
    for img in path_arr:
        result = pyautogui.locateAllOnScreen(img, grayscale=False, confidence=0.65)
        for pos in result:
            rectangles[i].append(pos)
            rectangles[i].append(pos)
    rectangles[i], weights = cv2.groupRectangles(rectangles[i], 1, 0.2)
    for j, pos in enumerate(rectangles[i]):
        b = int((pos[1] - (-0.217 * pos[0])) / 40)
        rectangles[i][j] = pos + (b,)
    if  len(rectangles[i]) > 1:
        print(rectangles[i])
        xvals = rectangles[i][:,0]
        yvals = rectangles[i][:,1]
        rectangles[i] = rectangles[i][np.lexsort((xvals, yvals))]
    print(len(rectangles[i]))
    for pos in rectangles[i]:
        cv2.rectangle(imsscvnew, (pos[0],pos[1]), (pos[0]+pos[2],pos[1]+pos[3]), (0,255,255), 2)
    cv2.imshow('Result', imsscvnew)
    cv2.waitKey()
    cv2.destroyAllWindows()

[[787 247  25  21]
 [755 254  25  21]]
2
[[ 666  467   31   29]
 [1004  327   38   34]
 [ 461  445   38   34]
 [ 365  643   36   31]]
4
[[207 406  23  24]
 [691 307  18  20]
 [361 319  16  18]
 [640 337  18  20]
 [559 375  19  21]
 [527 382  19  21]]
6
[[ 795  301   21   23]
 [ 808  317   21   23]
 [ 777  326   22   24]
 [ 667  329   21   23]
 [ 822  335   22   24]
 [ 635  336   21   23]
 [ 867  344   22   24]
 [ 680  345   21   23]
 [ 539  357   21   23]
 [ 804  358   22   24]
 [ 616  359   21   23]
 [ 771  365   22   24]
 [ 584  366   21   23]
 [ 849  368   23   25]
 [ 740  372   22   24]
 [ 552  373   21   23]
 [ 818  375   23   25]
 [ 488  387   21   23]
 [ 831  391   23   25]
 [ 644  392   22   24]
 [ 612  399   22   24]
 [ 690  403   23   25]
 [ 767  405   23   25]
 [ 846  408   24   26]
 [ 657  410   23   25]
 [ 548  413   22   24]
 [ 814  415   24   26]
 [1078  416   25   27]
 [ 626  417   23   25]
 [ 439  418   22   24]
 [ 703  419   23   25]
 [1046  423   25   27]
 [ 937  427

In [263]:
print(rectangles[1])

[[ 180  435   17   15]
 [ 240  414   25   21]
 [ 245  374   25   21]
 [ 258  437   17   15]
 [ 298  486   17   15]
 [ 359  377   17   15]
 [ 375  259   17   15]
 [ 420  268   17   15]
 [ 424  316   25   21]
 [ 495  358   25   21]
 [ 527  351   25   21]
 [ 559  344   25   21]
 [ 612  227   17   15]
 [ 618  370   25   21]
 [ 620  282   17   15]
 [ 625  243   17   15]
 [ 636  346   25   21]
 [ 649  362   25   21]
 [ 649  409   17   15]
 [ 657  236   17   15]
 [ 692  324   17   15]
 [ 697  284   17   15]
 [ 708  206   17   15]
 [ 713  395   17   15]
 [ 729  278   17   15]
 [ 734  238   17   15]
 [ 748  254   17   15]
 [ 764  361   17   18]
 [ 780  248   17   15]
 [ 796  358   17   15]
 [ 799  406   25   21]
 [ 814  335   17   15]
 [ 817  383   25   21]
 [ 937  342   17   18]
 [ 942  307   17   15]
 [ 956  324   17   15]
 [ 968  340   17   15]
 [ 974  300   17   15]
 [ 987  316   17   15]
 [1049  432   17   18]]


In [119]:
# Failed attempt at using a mask

# imss = pyautogui.screenshot('imss.png')
# img = cv2.imread('imss.png')

# template = cv2.imread(obj_pathnames[3], cv2.IMREAD_UNCHANGED)
# h, w = template.shape[:2]

# base = template[:,:,0:3]
# alpha = template[:,:,3]
# alpha = cv2.merge([alpha,alpha,alpha])

# correlation = cv2.matchTemplate(img, base, cv2.TM_CCORR_NORMED, mask=alpha)
# min_val, max_val, min_loc, max_loc = cv2.minMaxLoc(correlation)
# print(min_val)

# print(max_val)
# yloc, xloc = np.where(correlation >= 0.95)
# print(len(xloc))
# for (x, y) in zip(xloc, yloc):
#     cv2.rectangle(img, (x, y), (x + w, y + h), (0,255,255), 2)

2.3636352874945032e-09
inf
92490


In [120]:
cv2.imshow('Result', img)
cv2.waitKey()
cv2.destroyAllWindows()

In [157]:
#initial attempt at locateAllOnScreen: only used for one object at a time by altering the index of obj_pathnames

# imss = pyautogui.screenshot("imss.png")
# imsscv = cv2.imread('imss.png')
# rectangles = []
# result = pyautogui.locateAllOnScreen(obj_pathnames[2], grayscale=False, confidence=0.6)
# for pos in result:
#     rectangles.append(pos)
#     rectangles.append(pos)
# rectangles, weights = cv2.groupRectangles(rectangles, 1, 0.2)
# print(len(rectangles))
# for pos in rectangles:
#     cv2.rectangle(imsscv, (pos[0],pos[1]), (pos[0]+pos[2],pos[1]+pos[3]), (0,255,255), 2)

13


In [ ]:
cv2.imshow('Result', imsscv)
cv2.waitKey(0)
cv2.destroyAllWindows()
cv2.waitKey(1)

In [154]:
#second attempt at locateAllOnScreen: runs for every object and adds all triangles at the end


# imss = pyautogui.screenshot("imss.png")
# imsscv = cv2.imread('imss.png')
# rectangles = []
# for img in obj_pathnames:
#     result = pyautogui.locateAllOnScreen(img, grayscale=False, confidence=0.65)
#     for pos in result:
#         rectangles.append(pos)
#         rectangles.append(pos)
# rectangles, weights = cv2.groupRectangles(rectangles, 1, 0.2)
# print(len(rectangles))
# for pos in rectangles:
#     print(pos)
#     cv2.rectangle(imsscv, (pos[0],pos[1]), (pos[0]+pos[2],pos[1]+pos[3]), (0,255,255), 2)

251
[937 342  17  18]
[764 361  17  18]
[1049  432   17   18]
[708 206  17  15]
[612 227  17  15]
[657 236  17  15]
[734 238  17  15]
[625 243  17  15]
[780 248  17  15]
[748 254  17  15]
[375 259  17  15]
[420 268  17  15]
[729 278  17  15]
[620 282  17  15]
[697 284  17  15]
[974 300  17  15]
[942 308  17  15]
[987 316  17  15]
[692 324  17  15]
[956 324  17  15]
[814 335  17  15]
[968 340  17  15]
[796 358  17  15]
[359 377  17  15]
[713 395  17  15]
[649 409  17  15]
[180 435  17  15]
[258 437  17  15]
[298 486  17  15]
[424 316  25  21]
[559 344  25  21]
[636 346  25  21]
[527 351  25  21]
[495 358  25  21]
[649 363  25  21]
[913 362  25  21]
[618 370  25  21]
[245 374  25  21]
[817 383  25  21]
[799 406  25  21]
[240 414  25  21]
[398 332  15  11]
[438 380  15  11]
[310 408  15  11]
[555 431  15  11]
[600 440  15  11]
[390 505  15  11]
[403 521  15  11]
[680 537  15  11]
[757 540  15  11]
[725 546  15  11]
[694 554  14  11]
[349 362  12  12]
[671 388  12  12]
[748 390  12  12]
[4

In [ ]:
##cv2.imshow('Result', imsscv)
cv2.waitKey(0)
cv2.destroyAllWindows()
cv2.waitKey(1)

In [156]:
#Third view: runs each object and its rectangles individually allowing us to see mistakes

# imss = pyautogui.screenshot("imss.png")
# imsscv = cv2.imread('imss.png')
# rectangles = []
# for img in obj_pathnames:
#     imsscvnew = imsscv.copy()
#     print(img)
#     result = pyautogui.locateAllOnScreen(img, grayscale=False, confidence=0.65)
#     for pos in result:
#         rectangles.append(pos)
#         rectangles.append(pos)
#     rectangles, weights = cv2.groupRectangles(rectangles, 1, 0.2)
#     print(len(rectangles))
#     for pos in rectangles:
#         print(pos)
#         cv2.rectangle(imsscvnew, (pos[0],pos[1]), (pos[0]+pos[2],pos[1]+pos[3]), (0,255,255), 2)
#     cv2.imshow('Result', imsscvnew)
#     cv2.waitKey(0)
#     cv2.destroyAllWindows()
#     cv2.waitKey(1)
#     rectangles = []

Object_Images_Desktop\Dragon_Egg_Chest_Red.PNG
3
[937 342  17  18]
[764 361  17  18]
[1049  432   17   18]
Object_Images_Desktop\Dragon_Egg_Chest_Stone_test.PNG
52
[708 206  17  15]
[612 227  17  15]
[657 236  17  15]
[734 238  17  15]
[625 243  17  15]
[780 248  17  15]
[748 254  17  15]
[375 259  17  15]
[1889  266   17   15]
[420 268  17  15]
[729 278  17  15]
[620 282  17  15]
[697 284  17  15]
[1793  287   17   15]
[1838  296   17   15]
[1916  298   17   15]
[974 300  17  15]
[1806  303   17   15]
[942 308  17  15]
[1961  307   17   15]
[1929  314   17   15]
[987 316  17  15]
[1556  319   17   15]
[692 324  17  15]
[956 324  17  15]
[1602  328   17   15]
[814 335  17  15]
[1910  337   17   15]
[968 340  17  15]
[1801  342   17   15]
[1878  344   17   15]
[796 358  17  15]
[2155  360   17   15]
[2123  367   17   15]
[359 377  17  15]
[2168  376   17   15]
[1873  384   17   15]
[2136  384   17   15]
[713 395  17  15]
[1995  395   17   15]
[2150  400   17   15]
[649 409  17  15]
[197

In [9]:
## Emergency close all windows if the imshow doesn't close properly
cv2.waitKey(0)
cv2.destroyAllWindows()
cv2.waitKey(1)

-1

In [196]:
# imss = pyautogui.screenshot("imss.png")
# imsscv = cv2.imread('imss.png')
# rectangles = []
# result = pyautogui.locateAllOnScreen(obj_pathnames[8], grayscale=False, confidence=0.6)
# for pos in result:
#     rectangles.append(pos)
#     rectangles.append(pos)
# rectangles, weights = cv2.groupRectangles(rectangles, 1, 0.2)
# print(len(rectangles))
# for pos in rectangles:
#     cv2.rectangle(imsscv, (pos[0],pos[1]), (pos[0]+pos[2],pos[1]+pos[3]), (0,255,255), 2)

191


In [189]:
cv2.imshow('Result', imsscv)
cv2.waitKey(0)
cv2.destroyAllWindows()
cv2.waitKey(1)

-1

In [25]:
def click_Middle(x, y, w, h):
    pyautogui.click((x+0.5*w, y+0.5*h))

In [26]:
def double_Click_Middle(x, y, w, h):
    pyautogui.click((x+0.5*w, y+0.5*h))
    time.sleep(0.2)
    pyautogui.click((x+0.5*w, y+0.5*h))

In [114]:
## Goes through each rectangle array and does corresponding sequence to each object found

# first sort the rectangles in increasing x value

# iterate through rectangles arrays
# for selling options, if dragon power image is found, don't sell
## We should always check for cancel buttons at the end of each iteration to make sure we return to camp base state

## First Case, sell with one tap
## Cases for clicking magic merchant, dragons, two sell item, one tap item, two tap item
## Magic Merchant: if we see cancel button, click adn move on
## Dragons: if we see dragon power, move on to next click
## Two Sell Item: click the x and move on
## One Tap item: nothing its been clicked move on
## Two tap item: just pray its nothing important and if it is, cclick the cancel button at the end

# for pos in rectangles[0]:
#     click_Middle(*pos)
#     time.sleep(1)
# #    if we accidentally tapped a dragon, a sell two tap item, or something that cannot be sold
#     if pyautogui.locateOnScreen('Object_Images_Desktop\\Dragon_Power.png', grayscale=False, confidence=0.8, region=(650,550,200,200)):
#         time.sleep(0.5)
#         continue
#     if cancel_button := pyautogui.locateOnScreen('Object_Images_Desktop\\Cancel_Button.png', grayscale=False, confidence=0.9, region=(775,150,50,50)):
#         click_Middle(*cancel_button)
#         time.sleep(0.5)
#         continue
#     elif cancel_button := pyautogui.locateOnScreen('Object_Images_Desktop\\Cancel_Button_2.png', grayscale=False, confidence=0.9, region=(700,100,200,200)):
#         click_Middle(*cancel_button)
#         time.sleep(0.5)
#         continue
#     if sell_btn := pyautogui.locateOnScreen('Object_Images_Desktop\\Sell_Button.png', grayscale=False, confidence=0.8, region=(700, 600, 200,200)):
#         click_Middle(*sell_btn)
#     if cancel_button := pyautogui.locateOnScreen('Object_Images_Desktop\\Cancel_Button.png', grayscale=False, confidence=0.9, region=(775,150,50,50)):
#         click_Middle(*cancel_button)
#     elif cancel_button := pyautogui.locateOnScreen('Object_Images_Desktop\\Cancel_Button_2.png', grayscale=False, confidence=0.9, region=(700,100,200,200)):
#         click_Middle(*cancel_button)
#     time.sleep(0.5)

## Second Case, sell with two taps
## Cases for clicking magic merchant, dragons, one sell item, one tap item, two tap item
## Magic Merchant: There is no sell button, so we shouldnt have any action, at end, If we see cancel button, click it
## Dragons: Check dragon power png and if present, just continue to click smth else
## One Sell Item: no dark sell button so nothing should happen, simply move to next click
## Two sell item we don't want to sell: nothing should happen because theres no dark sell button, but
## check for unlock button before selling
## One Tap item: Doesn't matter, its been tapped
## Two Tap Item: Should probably not do anything because there will not be a dark sell button
# for pos in rectangles[1]:
#     click_Middle(*pos)
#     time.sleep(1)
#     if pyautogui.locateOnScreen('Object_Images_Desktop\\Dragon_Power.png', grayscale=False, confidence=0.8, region=(650,550,200,200)):
#         time.sleep(0.5)
#         continue
#     if sell_btn_dark := pyautogui.locateOnScreen('Object_Images_Desktop\\Sell_Button_Dark.png', grayscale=False, confidence=0.8, region=(700, 600, 200,200)):
#         if loc_unlock := pyautogui.locateOnScreen('Object_Images_Desktop/Unlock_Option.PNG', grayscale=False, confidence=0.8, region=(500,175,150, 50)):
#             print(loc_unlock)
#             click_Middle(*sell_btn_dark)
#             time.sleep(0.3)
#             click_Middle(*sell_btn_dark)
#             time.sleep(0.3)
#             if sell_btn_confirm := pyautogui.locateOnScreen('Object_Images_Desktop\\Sell_Button_Confirm.png', grayscale=False, confidence=0.8, region =(300,400,300,300)):
#                     click_Middle(*sell_btn_confirm)
#     if cancel_button := pyautogui.locateOnScreen('Object_Images_Desktop\\Cancel_Button.png', grayscale=False, confidence=0.9, region=(775,150,50,50)):
#         click_Middle(*cancel_button)
#     elif cancel_button := pyautogui.locateOnScreen('Object_Images_Desktop\\Cancel_Button_2.png', grayscale=False, confidence=0.9, region=(700,100,200,200)):
#         click_Middle(*cancel_button)
#     time.sleep(0.5)

## Third Case, tap once
# Cases for clicking magic merchant, two tap item, anything with a pop up
# Check for cancel buttons and click it
# for pos in rectangles[2]:
#     click_Middle(*pos)
#     time.sleep(1)
#     if cancel_button := pyautogui.locateOnScreen('Object_Images_Desktop\\Cancel_Button.png', grayscale=False, confidence=0.9, region=(775,150,50,50)):
#         click_Middle(*cancel_button)
#     elif cancel_button := pyautogui.locateOnScreen('Object_Images_Desktop\\Cancel_Button_2.png', grayscale=False, confidence=0.9, region=(700,100,200,200)):
#         click_Middle(*cancel_button)
#     time.sleep(0.5)

## Fourth Case, tap twice
# Cases for clicking something with a popup
# inbetween clicks check for cancel buttons and if there is, click out and continue
num_harvested = 0
for i in range(num_harvested, min(num_harvested+15, len(rectangles[3]))):
    pos = rectangles[3][i]
    num_harvested += 1
    click_Middle(*pos)
    time.sleep(0.3)
    if cancel_button := pyautogui.locateOnScreen('Object_Images_Desktop\\Cancel_Button.png', grayscale=False, confidence=0.9, region=(775,150,50,50)):
        click_Middle(*cancel_button)
        time.sleep(0.5)
        continue
    elif cancel_button := pyautogui.locateOnScreen('Object_Images_Desktop\\Cancel_Button_2.png', grayscale=False, confidence=0.9, region=(700,100,200,200)):
        click_Middle(*cancel_button)
        time.sleep(0.5)
        continue
    click_Middle(*pos)
    if cancel_button := pyautogui.locateOnScreen('Object_Images_Desktop\\Cancel_Button.png', grayscale=False, confidence=0.9, region=(775,150,50,50)):
        click_Middle(*cancel_button)
    elif cancel_button := pyautogui.locateOnScreen('Object_Images_Desktop\\Cancel_Button_2.png', grayscale=False, confidence=0.9, region=(700,100,200,200)):
        click_Middle(*cancel_button)
    time.sleep(0.5)


    
#for pos in rectangles[1]
#for pos in rectangles[2]
#for pos in rectangles[3]

#print(pyautogui.locateOnScreen('Object_Images_Desktop\\Dragon_Power.png', grayscale=False, confidence=0.8, region=(650,550,200,200)))

In [37]:
## Test first rectangle of arr 2: Sell One Tap
pos = rectangles[0][0]
click_Middle(*pos)
time.sleep(1)
#    if we accidentally tapped a dragon, a sell two tap item, or something that cannot be sold
if pyautogui.locateOnScreen('Object_Images_Desktop\\Dragon_Power.png', grayscale=False, confidence=0.8, region=(650,550,200,200)):
    time.sleep(0.5)
if cancel_button := pyautogui.locateOnScreen('Object_Images_Desktop\\Cancel_Button.png', grayscale=False, confidence=0.9, region=(775,150,50,50)):
    click_Middle(*cancel_button)
    time.sleep(0.5)
elif cancel_button := pyautogui.locateOnScreen('Object_Images_Desktop\\Cancel_Button_2.png', grayscale=False, confidence=0.9, region=(700,100,200,200)):
    click_Middle(*cancel_button)
    time.sleep(0.5)
if sell_btn := pyautogui.locateOnScreen('Object_Images_Desktop\\Sell_Button.png', grayscale=False, confidence=0.8, region=(700, 600, 200,200)):
    click_Middle(*sell_btn)
if cancel_button := pyautogui.locateOnScreen('Object_Images_Desktop\\Cancel_Button.png', grayscale=False, confidence=0.9, region=(775,150,50,50)):
    click_Middle(*cancel_button)
elif cancel_button := pyautogui.locateOnScreen('Object_Images_Desktop\\Cancel_Button_2.png', grayscale=False, confidence=0.9, region=(700,100,200,200)):
    click_Middle(*cancel_button)
time.sleep(0.5)

In [ ]:
## Test first rectangle of arr 2: Sell Two Tap 
pos = rectangles[1][0]
click_Middle(*pos)
time.sleep(1)
if pyautogui.locateOnScreen('Object_Images_Desktop\\Dragon_Power.png', grayscale=False, confidence=0.8, region=(650,550,200,200)):
    time.sleep(0.5)
if sell_btn_dark := pyautogui.locateOnScreen('Object_Images_Desktop\\Sell_Button_Dark.png', grayscale=False, confidence=0.8, region=(700, 600, 200,200)):
    if pyautogui.locateOnScreen('Object_Images_Desktop/Unlock_Option.PNG', grayscale=False, confidence=0.8, region=(500,175,170, 60)):
        click_Middle(*sell_btn_dark)
        time.sleep(0.3)
        click_Middle(*sell_btn_dark)
        time.sleep(0.3)
        if sell_btn_confirm := pyautogui.locateOnScreen('Object_Images_Desktop\\Sell_Button_Confirm.png', grayscale=False, confidence=0.8, region =(300,400,300,300)):
                click_Middle(*sell_btn_confirm)
if cancel_button := pyautogui.locateOnScreen('Object_Images_Desktop\\Cancel_Button.png', grayscale=False, confidence=0.9, region=(775,150,50,50)):
    click_Middle(*cancel_button)
elif cancel_button := pyautogui.locateOnScreen('Object_Images_Desktop\\Cancel_Button_2.png', grayscale=False, confidence=0.9, region=(700,100,200,200)):
    click_Middle(*cancel_button)
time.sleep(0.5)

In [74]:
## Test first position for tap once
pos = rectangles[2][1]
click_Middle(*pos)
time.sleep(1)
if cancel_button := pyautogui.locateOnScreen('Object_Images_Desktop\\Cancel_Button.png', grayscale=False, confidence=0.9, region=(775,150,50,50)):
    click_Middle(*cancel_button)
elif cancel_button := pyautogui.locateOnScreen('Object_Images_Desktop\\Cancel_Button_2.png', grayscale=False, confidence=0.9, region=(700,100,200,200)):
    click_Middle(*cancel_button)
time.sleep(0.5)
pos = rectangles[2][2]
click_Middle(*pos)
time.sleep(1)
if cancel_button := pyautogui.locateOnScreen('Object_Images_Desktop\\Cancel_Button.png', grayscale=False, confidence=0.9, region=(775,150,50,50)):
    click_Middle(*cancel_button)
elif cancel_button := pyautogui.locateOnScreen('Object_Images_Desktop\\Cancel_Button_2.png', grayscale=False, confidence=0.9, region=(700,100,200,200)):
    click_Middle(*cancel_button)
time.sleep(0.5)

In [104]:
## Test for first position for tap twice
pos = rectangles[3][1]
click_Middle(*pos)
time.sleep(0.3)
if cancel_button := pyautogui.locateOnScreen('Object_Images_Desktop\\Cancel_Button.png', grayscale=False, confidence=0.9, region=(775,150,50,50)):
    click_Middle(*cancel_button)
    time.sleep(0.5)
elif cancel_button := pyautogui.locateOnScreen('Object_Images_Desktop\\Cancel_Button_2.png', grayscale=False, confidence=0.9, region=(700,100,200,200)):
    click_Middle(*cancel_button)
    time.sleep(0.5)
else:
    click_Middle(*pos)
    if cancel_button := pyautogui.locateOnScreen('Object_Images_Desktop\\Cancel_Button.png', grayscale=False, confidence=0.9, region=(775,150,50,50)):
        click_Middle(*cancel_button)
    elif cancel_button := pyautogui.locateOnScreen('Object_Images_Desktop\\Cancel_Button_2.png', grayscale=False, confidence=0.9, region=(700,100,200,200)):
        click_Middle(*cancel_button)
    time.sleep(0.5)

idgaf


In [211]:
rectangles

array([[117, 356,  10,  12],
       [144, 388,  10,  12],
       [157, 404,  10,  12],
       [162, 365,  10,  12],
       [189, 398,  10,  12],
       [194, 358,  10,  12],
       [197, 453,  10,  12],
       [202, 414,  10,  12],
       [215, 430,  10,  12],
       [221, 390,  10,  12],
       [228, 446,  10,  12],
       [242, 462,  10,  12],
       [263, 534,  10,  12],
       [266, 400,  10,  12],
       [274, 455,  10,  12],
       [279, 416,  10,  12],
       [282, 510,  10,  12],
       [285, 377,  10,  12],
       [287, 471,  10,  12],
       [290, 566,  10,  12],
       [292, 432,  10,  12],
       [298, 393,  10,  12],
       [303, 582,  10,  12],
       [304, 354,  10,  12],
       [306, 448,  10,  12],
       [314, 504,  10,  12],
       [317, 370,  10,  12],
       [319, 464,  10,  12],
       [322, 330,  10,  12],
       [322, 559,  10,  12],
       [324, 425,  10,  12],
       [327, 520,  10,  12],
       [330, 386,  10,  12],
       [332, 480,  10,  12],
       [335, 3

In [116]:
import pyautogui, sys
print('Press Ctrl-C to quit.')
try:
    while True:
        x, y = pyautogui.position()
        positionStr = 'X: ' + str(x) + ' Y: ' + str(y)
        print(positionStr, end='')
        time.sleep(5)
except KeyboardInterrupt:
    print('\n')

Press Ctrl-C to quit.
X: 342 Y: 330X: 602 Y: 275



In [135]:
(275-330)/(602 - 342)

-0.21153846153846154

In [136]:
(219-351)/(725-118)

-0.21746293245469522

In [144]:
(314-432)/(991-447)

-0.21691176470588236

In [88]:
pyautogui.moveTo((674,103))

In [ ]:
## Important Measurements:
# Cancel Buttons: 700, 100, 200, 200
# Slope of line which camp is oriented around: (219-351)/(725-118) = -0.21746293245469522
# (353-513)/(986-250) = -0.21739130434782608
# (314-432)/(991-447) = -0.21691176470588236