In [3]:
!pip install opencv-python
!pip install pyautogui

     |████████████████████████████████| 59 kB 1.7 MB/s eta 0:00:01
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
     |████████████████████████████████| 578 kB 4.9 MB/s eta 0:00:01
     |████████████████████████████████| 58 kB 13.0 MB/s eta 0:00:01
     |████████████████████████████████| 226 kB 52.9 MB/s eta 0:00:01
     |████████████████████████████████| 388 kB 27.6 MB/s eta 0:00:01
     |████████████████████████████████| 45 kB 7.7 MB/s  eta 0:00:01


     |████████████████████████████████| 40 kB 12.2 MB/s eta 0:00:01
  Created wheel for pyautogui: filename=PyAutoGUI-0.9.53-py3-none-any.whl size=36613 sha256=f0efacbee949d27d78b13a93012ded2d90b25b54517abaa98a843e0486d75750
  Stored in directory: /Users/brandonliu/Library/Caches/pip/wheels/d8/97/e4/d2edca92a87d3b5fbfb527264750a17b4ba297b9a7cab6e67f
  Created wheel for pygetwindow: filename=PyGetWindow-0.0.9-py3-none-any.whl size=11080 sha256=c12fb09aebb6e02b0522aabef681058a177f113d91fa3e9ccf9a5aed5bbfc7bf
  Stored in directory: /Users/brandonliu/Library/Caches/pip/wheels/44/ab/20/423c3a444793767e4e41f8377bc902f77bee212e68dcce85a5
  Created wheel for pyscreeze: filename=PyScreeze-0.1.28-py3-none-any.whl size=13009 sha256=8e8d5ea9a8d71298a4db2891c36141d04d73edac68fa4ec186071ce5304a334f
  Stored in directory: /Users/brandonliu/Library/Caches/pip/wheels/a2/5b/86/99f1d8fac5d92de0ccb3f0d4ad15e3f4278baf75a9b0f20b93
  Created wheel for PyTweening: filename=pytweening-1.0.4-py3-none-any.whl si

In [2]:
import cv2
import numpy as np
import os
import pyautogui

In [4]:
board_img = cv2.imread('camp_img.png')
obj_pathnames = []
obj_arr = []
directory = 'Object_Images'

for filename in os.listdir(directory):
    if filename[0] != '.':
        f = os.path.join(directory, filename)
        # checking if it is a file
        if os.path.isfile(f):
            obj_pathnames.append(f)
            obj_arr.append(cv2.imread(f, cv2.IMREAD_UNCHANGED))
    
 
# iterate over files in
# that directory
#for filename in os.scandir(directory):
 #   if filename.is_file() and filename.path[0] != '.':
  #      obj_pathnames.append(filename.path)
   #     obj_arr.append(cv2.imread(filename.path, cv2.IMREAD_UNCHANGED))
print(obj_pathnames)
print(len(obj_pathnames))

['Object_Images/Magic_Coin_Bronze.png', 'Object_Images/Tiny_Magic_Coin.png', 'Object_Images/Emerald_Plains_Grass.png', 'Object_Images/Radiant_Egg_Chest_Wooden.png', 'Object_Images/Dragon_Egg_Chest_Red.png', 'Object_Images/Dragon_Egg_Chest_Stone.png', 'Object_Images/Dragon_Nest_Vault_Stone.png']
7


In [109]:
imss = pyautogui.screenshot("imss.png")
imsscv = cv2.imread('imss.png')
rectangles = []
for img in obj_pathnames:
    result = pyautogui.locateAllOnScreen(img, grayscale=True, confidence=0.65)
    for pos in result:
        rectangles.append(pos)
        rectangles.append(pos)
rectangles, weights = cv2.groupRectangles(rectangles, 1, 0.2)
print(len(rectangles))
for pos in rectangles:
    print(pos)
    cv2.rectangle(imsscv, (pos[0],pos[1]), (pos[0]+pos[2],pos[1]+pos[3]), (0,255,255), 2)

67
[1581  774   35   35]
[347 175  38  32]
[410 195  38  32]
[1555  748   38   32]
[1569  965   38   32]
[ 233 1009   38   32]
[1721 1079   38   32]
[1523 1098   38   32]
[738 604  35  35]
[644 659  35  35]
[813 694  35  35]
[1246  706   35   35]
[1389  710   35   35]
[922 740  35  35]
[574 745  35  35]
[863 754  35  35]
[311 767  35  35]
[803 766  35  35]
[1032  788   35   35]
[1116  805   35   35]
[723 926  35  35]
[748 956  35  35]
[1265  986   35   35]
[1409  991   35   35]
[ 509 1008   35   35]
[616 499  39  39]
[1615  727   39   39]
[1746  633   34   34]
[1423  668   34   34]
[872 678  34  34]
[1318  377   34   31]
[1139  416   34   31]
[1223  433   34   31]
[1368  437   34   31]
[1164  446   34   31]
[1452  454   34   31]
[1392  467   34   31]
[697 476  34  31]
[781 494  34  31]
[1356  510   34   31]
[1154  519   34   31]
[1297  523   34   31]
[1814  553   34   31]
[1755  566   34   31]
[1780  596   34   31]
[1288  596   34   31]
[1516  618   34   31]
[1804  626   34   31]
[1481

In [110]:
cv2.imshow('Result', imsscv)
cv2.waitKey(0)
cv2.destroyAllWindows()
cv2.waitKey(1)

-1

In [16]:
imss = pyautogui.screenshot("imss.png")
imsscv = cv2.imread('imss.png')
rectangles = []
for img in obj_pathnames:
    imsscvnew = imsscv.copy()
    print(img)
    result = pyautogui.locateAllOnScreen(img, grayscale=False, confidence=0.65)
    for pos in result:
        rectangles.append(pos)
        rectangles.append(pos)
    rectangles, weights = cv2.groupRectangles(rectangles, 1, 0.2)
    print(len(rectangles))
    for pos in rectangles:
        print(pos)
        cv2.rectangle(imsscvnew, (pos[0],pos[1]), (pos[0]+pos[2],pos[1]+pos[3]), (0,255,255), 2)
    cv2.imshow('Result', imsscvnew)
    cv2.waitKey(0)
    cv2.destroyAllWindows()
    cv2.waitKey(1)
    rectangles = []

Object_Images/Magic_Coin_Bronze.png
8
[2001   94   23   25]
[1962   94   23   25]
[49 98 23 25]
[89 98 23 25]
[129  98  23  25]
[1832  222   23   25]
[573 768  23  25]
[1425  806   23   25]
Object_Images/Tiny_Magic_Coin.png
3
[1194  535   38   32]
[780 718  38  32]
[1395  779   38   32]
Object_Images/Emerald_Plains_Grass.png
1
[278 795  35  35]
Object_Images/Radiant_Egg_Chest_Wooden.png
1
[1448  759   39   39]
Object_Images/Dragon_Egg_Chest_Red.png
3
[1566  674   34   34]
[1276  706   34   34]
[1753  826   34   34]
Object_Images/Dragon_Egg_Chest_Stone.png
26
[1182  445   34   31]
[1021  480   34   31]
[1097  496   34   31]
[1226  499   34   31]
[1044  507   34   31]
[1302  515   34   31]
[1249  526   34   31]
[625 535  34  31]
[700 550  34  31]
[1217  565   34   31]
[1035  573   34   31]
[1164  577   34   31]
[1628  604   34   31]
[1574  615   34   31]
[1650  630   34   31]
[1596  642   34   31]
[1155  642   34   31]
[1360  662   34   31]
[1619  669   34   31]
[1328  701   34   31]
[59

In [14]:
cv2.waitKey(0)
cv2.destroyAllWindows()
cv2.waitKey(1)

-1

In [15]:
cv2.destroyAllWindows()